export const strings = {
  common: {
    loading: 'Carregando...',
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    confirm: 'Confirmar',
    edit: 'Editar',
    back: 'Voltar',
    next: 'Próximo',
    done: 'Concluído',
    search: 'Buscar',
    retry: 'Tentar novamente',
    error: 'Algo deu errado',
  },
  auth: {
    login: 'Entrar',
    register: 'Criar conta',
    email: 'E-mail',
    password: 'Senha',
    fullName: 'Nome completo',
    forgotPassword: 'Esqueceu a senha?',
    noAccount: 'Não tem conta?',
    hasAccount: 'Já tem conta?',
    magicLink: 'Entrar com link mágico',
    magicLinkSent: 'Link enviado! Verifique seu e-mail.',
  },
  onboarding: {
    step1Title: 'Bem-vindo ao FitPro!',
    step1Subtitle: 'O app para profissionais de atividades físicas e seus alunos.',
    step2Title: 'Qual é o seu perfil?',
    step2Teacher: 'Sou Professor(a)',
    step2Student: 'Sou Aluno(a)',
    step3TeacherTitle: 'Configure seu perfil',
    step3StudentTitle: 'Seus dados',
  },
  teacher: {
    dashboard: 'Painel',
    classes: 'Turmas',
    schedule: 'Agenda',
    chat: 'Chat',
    profile: 'Perfil',
    students: 'Alunos',
    finances: 'Financeiro',
    activeStudents: 'Alunos ativos',
    todayClasses: 'Aulas hoje',
    monthRevenue: 'Receita do mês',
    overdue: 'Inadimplentes',
    newClass: 'Nova Turma',
    inviteStudent: 'Convidar Aluno',
  },
  student: {
    dashboard: 'Início',
    myClasses: 'Minhas Aulas',
    schedule: 'Agenda',
    chat: 'Chat',
    profile: 'Perfil',
    confirmAttendance: 'Confirmar Presença',
    cancelAttendance: 'Cancelar Presença',
    nextClasses: 'Próximas Aulas',
    myProgress: 'Meu Progresso',
    pendingPayments: 'Pagamentos Pendentes',
  },
  empty: {
    noClasses: 'Nenhuma turma ainda',
    noClassesCta: 'Crie sua primeira turma!',
    noStudents: 'Nenhum aluno ainda',
    noStudentsCta: 'Convide seus alunos!',
    noMessages: 'Nenhuma mensagem',
    noMessagesCta: 'Envie a primeira mensagem!',
    noPayments: 'Nenhum pagamento',
  },
} as const;
